### ISSUE TITLE
Помещения для животных

### ISSUE THREAD

**Issue by Oleh-Verhulenko** [Arbitas/Cloud-Farm#11]
Реализовать помещения для животных.
https://projects.invisionapp.com/share/63607LEQP#/screens/134908130

Действия с помещениями:
+ помещения можно купить (докупать), 
наличие необходимых помещений на аккаунте устанавливает лимит на количество возможных птиц для содержания. 
+ помещения можно выставить на продажу на Рынке по свободной цене. 
+ администратор может добавлять и удалять помещения у выбранного пользователя.

Купленные пользователем помещения отображаются в Моей ферме.

У нас должна быть цепочка этапов, в случае с перепелками это яйцо - суточный цыпленок - 18 дневный - 30 дневный - взрослая птица (половозрастные группы). Для половозрастной группы мы определяем необходимость наличия места.

Если у нас израсходован лимит доступных для продажи мест, мы создаем новый лот с местами (в том числе при необходимости пишем сроки ожидания, если предзаказ).

Стоимость места в нашем первом лоте 170 руб, количество мест 12000.  Стоимость места и количество в последующих лотах может отличаться.

Если место не используется (без птицы), в каком-то будущем будем начислять расходы за содержания места (сейчас и в ближайшем будущем не актуально).

При покупке: если для данной половозрастной группы обязательно наличие места, то в корзину оно докидывается автоматически.

В случае, если при достижении новой возрастной группы и переходе из одной группы в другую пользователю могут понадобится дополнительные места. Мы информируем его через блок в шапке https://yadi.sk/i/HpfYR_3z357ooK формируем ссылку, при переходе по которой он попадает в корзину с добавленным необходимым количеством мест для покупки.
https://projects.invisionapp.com/share/63607LEQP#/screens/134908129
Если предупреждения игнорируются — происходит автопродажа перепелки.

Для каждого вида животного предусмотрено своё помещение.

**Comment by AeroLexx** [comment]
описание этой задачи уже не актуально, частично выполнено, частично требования изменены
