### ISSUE TITLE
Дата рождения и возраст животного

### ISSUE THREAD

**Issue by Oleh-Verhulenko** [Arbitas/Cloud-Farm#117]
В карточке животного выводить возраст и дату рождения http://облачная-ферма.рф/my-farm/animal/6343/

**Comment by samusevalexunsued** [comment]
Ссылка на страницу животного доступна пользователю только в том случае если животное не в группе, если оно в группе то есть ссылка только на группу. Что выводить в группе где много животных?

**Comment by AeroLexx** [comment]
Вывел дату рождения и возраст, но только в карточке одного животного, как и было показано в задании
