### ISSUE TITLE
Реализовать ссылки

### ISSUE THREAD

**Issue by Oleh-Verhulenko** [Arbitas/Cloud-Farm#118]
http://joxi.ru/Y2LkJBeU9V0Ram - реализовать ссылки на страницы животных

— ссылка на животное будет действительна только до тех пор, пока у пользователя есть это животное, а потом (в случае продажи) ссылка будет вести на 404
— можно и красивее это обыграть, но даже если в ситуации после продажи животного будет 404, мы можем на это сейчас смело закрыть глаза. А вот при наличии ссылки пользователь сможет увидеть, за что именно он получил деньги. Мне, как пользователю этой возможности не хватает!

— Ссылка на страницу животного доступна пользователю только в том случае если животное не в группе, если оно в группе то есть ссылка только на группу. 
— в группе же животные одного возраста? Группировка должна быть с учетом даты рождения в том числе. Даты разные - разные группы.

**Comment by samusevalexunsued** [comment]
Журнал - постоянная сущность, если в него что-то записано, изменить это уже нельзя, ссылка на животное будет действительна только до тех пор, пока у пользователя есть это животное, а потом ссылка будет вести на 404. Получится ситуация где у пользователя со временем в журнале будет куча "мертвых" ссылок.

**Comment by AeroLexx** [comment]
добавлено поле hash в таблицу 'animals'
добавлено поле hash в таблицу 'real_places'

добавлено поле hash в таблицу 'incubators_order'
ALTER TABLE `incubators_order` ADD `hash` VARCHAR(255) NOT NULL AFTER `object_count`;

**Comment by AeroLexx** [comment]
Добавил ссылку в журнале для событию Поставки. Ждём выгрузки
