### ISSUE TITLE
Перенос Фермы на новый сервер

### ISSUE THREAD

**Issue by Oleh-Verhulenko** [Arbitas/Cloud-Farm#119]
Сюда нужно перенести Ферму:
IP-адрес сервера : 82.146.39.154
Пользователь : root
Пароль : 3Ox8vpTbv53

**Comment by samusevalexunsued** [comment]
Пароль неправильный

**Comment by AeroLexx** [comment]
Пароль неверный не могу зайти (подключение SFTP)

**Comment by samusevalexunsued** [comment]
3Ox8vpTbv53r

**Comment by AeroLexx** [comment]
104LoGh8 - пароль для Mysql пользователь - root

**Comment by AeroLexx** [comment]
Перенёс сайт на новый сервер, настроил прокси
