### ISSUE TITLE
Скрыть текст в Моей ферме

### ISSUE THREAD

**Issue by Oleh-Verhulenko** [Arbitas/Cloud-Farm#120]
http://joxi.ru/8235PELsJGP6zr - скрыть этот текст только в разделе Моя ферма, т.к. она вводит в заблуждение пользователей.

Ясное дело, что быстрое решение этой задачи — костыльное, но постарайтесь, сделать максимально корректно и быстро.

**Comment by AeroLexx** [comment]
ожидаем выгрузки

**Comment by AeroLexx** [comment]
выгрузил
