### ISSUE TITLE
Правки от пользователя (рассмотреть)

### ISSUE THREAD

**Issue by Oleh-Verhulenko** [Arbitas/Cloud-Farm#124]
Хотелось бы видеть сколько животным дней, 
не понятно когда их продавать, 
и не видно у каких животных есть места, у каких нет, то же не удобно((

**Comment by AeroLexx** [comment]
1. В карточках животных в моей ферме, можем выводить возраст животного в днях, это не проблема
2. Когда нет места для животного в карточке это написано, может быть не так это бросается в глаза, можем переделать дизайн и сделать эту надпись более видной, можно так же добавить надпись что место есть в карточках.
