### ISSUE TITLE
Получить ответы на вопросы

### ISSUE THREAD

**Issue by Oleh-Verhulenko** [Arbitas/Cloud-Farm#15]
1. Что должно происходить при смене вида животного к которому привязано помещение? Например вот есть помещение для перепелов и вдруг по каким то причинам админ меняет что это помещение для гусей. 
http://joxi.ru/Vm6yRM5uDvDNEr
Тут может быть два варианта: 
а) запретить смену вида животных для помещений в админке, если вид уже был выбран (избегаем такой ситуации)
б) оставляем смену вида для помещений + они должны скинуть последовательность действий что должно произойти в такой случае.

2.  "помещения можно выставить на продажу на Рынке по свободной цене." ( http://joxi.ru/vAWDp5RF1O1e0r ) как я понимаю нужно будет открыть вот этот раздел для всех на сайте http://joxi.ru/1A5bagQInbn3lr, и должна быть покупка помещений для данного раздела.  Как я понимаю покупка помещений из этого раздела будет иметь  свои особенности - своя уникальная цена, отдельная карточка в корзине. 
P. S. Как я вижу задачи пока выставлять животных на продажу нет и пока не планируется.

3. "Купленные пользователем помещения отображаются в Моей ферме." joxi.ru/gmvR9d6SL1Laom
Вывод помещений расположили по ссылке на фильтр в моей ферме http://joxi.ru/5mdk3xNik8kWvr, если это неверно, напишите точно места вывода помещений в моей ферме - **верность подтверждена**

4. http://joxi.ru/823OKJnsJ8J0z2 - что такое лот? Это новое помещение имеется в виду? Например когда закончились места в перепёльне №1, создаем перепёльню №2 со своим набором мест ? (Для Олега: это главный вопрос, от ответа на него зависит постановка вопросов по предзаказу и срокам ожидания)

5. "При покупке: если для данной половозрастной группы обязательно наличие места, то в корзину оно докидывается автоматически" http://joxi.ru/DmBX0a1Iw4wLEA

Точно ли помещения должны автоматически добавлятся в корзину? 
Этот момент будет очень не ясен для пользователей (почему при добавлении товара в корзину ему автоматически докинулось что-то еще). 
Возможно стоит просто выводить предупреждение о том что ему не хватает помещений (с учетом того что  будут ситуации когда пользователю будет не доставать помещений).

6. Отсутвие помещения в данный момент для животного влияет как то на доход и расход приносимый животным?

7. Между этими двумя пунктами нужно ввести ясность joxi.ru/l2ZvQdnIw7wxM2 . Автоматически докидываем ТОЛЬКО при покупке, то есть при заходе в корзину, правильно? а в остальных случаях только предупреждение, потомучто сейчас мы докидываем их всегда.

8. При покупке новых животных должны ли учитываться недостающие помещения для уже существующих животных?

9. Написано что должно быть автопродажа животных без помещений, если пользователь игнорирует предупреждения. Однако не сказано: 
9.1. Сколько времени должно пройти со времени получения предупреждения до автопродажи?
9.2. Что делать если пользователь не долго не заходит на сайт?

**Comment by Oleh-Verhulenko** [comment]
**9.**
По блокировке пользователей:
Если на балансе пользователя сумма меньше необходимой для содержания его хозяйства 3-х суток, то пользователь не может совершать покупок новых животных и мест. 
Любой образовавшийся минус моментально автоматически ликвидируется за счёт продажи хозяйства (животных) на специальный страховой аккаунт (в первую очередь самые дешевые животные и далее по возрастающей стоимости), с него и будут поступать средства на погашение долга. 
Животные у пользователя будут выкупаться с дисконтом в 10%, т.е., на счёт пользователя для погашения задолженности поступит 90% суммы от продажи его животных. 
Животные пользователя будут выставлены на продажу на Рынке. Пользователь будет иметь первоочерёдное право в покупке (в случае если одумается и решит восстановить распроданное хозяйство).

"По вышеизложенным пунктам от себя добавлю: думаю можно было бы помещать распроданных животных в резерв на 3-5 дней (на сколько дней хватит средств дисконта) если пользователь по определённым форс-мажорным обстоятельствам не смог вовремя внести средства на счёт (в случае с перепелкой или курицей, конечно, вряд ли кто будет сокрушаться от потери, а вот когда это будет овечка, коза или страус, то тут явно есть что терять). В течение этого резерва животное можно будет показать на Рынке, но либо с надписью "Доступно к продаже будет ... числа", либо сделать полупрозрачную кнопку "Купить" в карточке данного животного и при наведении  появлялась все та же надпись. 
Как вы считаете?"

**Comment by Oleh-Verhulenko** [comment]
**2.**
На мой взгляд, должны быть как и вместе с животными, так и отдельно. В карточках половозрастных групп можно было бы разместить ссылку "Смотреть места" либо слева под фразой "Цена ... руб.", либо в правом нижнем углу слева от "Купить".

http://joxi.ru/E2pb4XeF97wjzr

В разделе Рынка "Помещения" в карточке каждого вида помещения можно было бы разместить ссылку, сделанную в духе Дмитрия Сафронова, в виде барашка или облачка с надписью типа "А теперь посмотрим кого можно в этом месте поселить" клик по которому перекинет на страницу подходящего месту животного.

http://joxi.ru/D2P85GeFpqvWQ2

http://joxi.ru/vAWyavlt1gGK3m

**Comment by AeroLexx** [comment]
2 - Тут нет ответа на сам вопрос((
9 - Решение отличное, я так понимаю что блокировки пользователей больше уже не будет как таковой, будет автопродажа майна

**Comment by Oleh-Verhulenko** [comment]
мультивыбор животных на продажу из группы https://yadi.sk/i/gABMRJuP38SGpR - решит проблему продажи конкретного животного.

**Comment by Oleh-Verhulenko** [comment]
**Пополнение счёта:**
+ Нужно дополнительно прикрутить прием яндекс.денег (https://money.yandex.ru/embed/quickpay/shop.xml?from=iget&_openstat=iget%3Bshop%3Bicon)
+ в довесок у них есть еще "Платежи со счета мобильного телефона"
+ подключить необходимо Купивкредит
Добрый день.
Так как Ваша компания утверждена, Вы уже можете начать процесс интеграции с тестовыми параметрами.
 Для понимания процесса интеграции сервиса «КупиВкредит» рекомендуем Вам просмотреть видео:https://youtu.be/EJXNuS9gz28
 
Этапы интеграции сервиса КупиВкредит:
 
1.  Провести техническую интеграцию формы кредитной заявки.
На сайте www.kupivkredit.ru находится список готовых решений для интеграции сервиса «Купи В Кредит». Для этого необходимо перейти во вкладку «Как присоединиться» и выбрать раздел «Модули для популярных CMS». Если в списке готовых модулей нет Вашей CMS или Ваш сайт самописный, значит Вам необходимо реализовать интеграцию самостоятельно. Примеры кода для интеграции формы Вы можете найти на сайте: http://form.kupivkredit.ru/developers/. Там же находится пример открытия формы кредитной заявки.
Данные для тестирования:
 
Интеграция формы
Идентификатор магазина (partnerId):
a06m00000018y7rAAA
Секретная строка (APIsecret/secretPhrase):
grid-secret-18y7r72a
URL подключения скрипта:

https://form-test.kupivkredit.ru/sdk/v1/sdk.js
Тестирование API
Ключ API (apiKey):
172a92d049cd48507f0f5594d8db2793
URL API:

https://kupivkredit-test-api.tcsbank.ru
 
URL подключения скрипта указывается только в том случае, если Вы реализовываете интеграцию согласно инструкцииhttp://form.kupivkredit.ru/developers/, в остальных случаях достаточно просто выбрать «Тестовый режим».
 
ВНИМАНИЕ: техподдержка КупиВкредит не занимается разработкой и отладкой кода на партнерских сайтах, не запрашивает доступы к админ-панели, а также не проводит интеграцию готовых решений на Ваш сайт во избежание утечки Вашей личной информации и потери работоспособности интернет-магазина.
 
Для владельцев сайтов на платформе InSales: обязательно в ответе на это письмо сообщите техподдержке, что Ваш сайт работает на платформе InSales!
Для владельцев сайтов на основе конструкторов (LPgenerator, WIX, Nethouse и др.): обязательно в ответе на это письмо сообщите техподдержке, что Ваш сайт работает на конструкторе и сообщите название конструктора!
 
2.  Оформить тестовую заявку.
При оформлении заявки в тестовом режиме в поле смс-код ввести 1010.
 
3.  Разместить кнопку «КупиВкредит» в карточке товара.
Варианты визуального оформления Вы можете найти на странице www.kupivkredit.ru/requirement. Выбирайте свой вариант в зависимости от особенностей реализации Вашего сайта. Если Вы используете готовое решение, то изменять ничего не нужно, так как все готовые модули прошли техническую проверку и соответствуют предъявляемым требованиям. Если внедрение кнопки вызывает затруднение, можно ограничиться текстовой информацией о возможности покупки в кредит, со ссылкой на более подробную информацию, например: «Вы можете купить этот товар в кредит. Подробнее…»
 
4.  Разместить информацию о сервисе КупиВкредит.
Рекомендуем описание/промо и, желательно, видео разместить в разделе «Оплата» или на отдельной странице. Информацию/промо вкладываю в письмо, ссылка на видео: https://youtu.be/-ZRSMYqM3I8
 
5.  По готовности интеграции пройти проверку нашим специалистом.
Написать письмо с темой «Проверка интеграции» на vkredit-helpdesk@tinkoff.ru. Специалисты КупиВкредит оформят тестовую заявку на Вашем сайте, проверят открытие формы, корректность передачи данных с Вашего сайта в Банк, а также визуальное оформление.
 
6.  Заменить тестовые параметры на реальные.
После проверки интеграции, и заключения договора присоединения, Вы получите рабочие параметры, Вам необходимо прописать их вместо тестовых, а также изменить адрес подключения скрипта на рабочий. Если после смены параметров форма открывается без ошибок, интеграцию можно считать завершенной.
 
7.  Получить доступ в Личный Кабинет для управления с кредитными заявками.
Для работы с заявками используется личный кабинет. При необходимости работы с заявками через админ-панель интернет-магазина Вам необходимо реализовать интеграцию по API. https://www.kupivkredit.ru/download/documents/API_Kupivkredit.docx

**Comment by Oleh-Verhulenko** [comment]
**Продажа помещений:**
https://yadi.sk/i/DI5gfos438gfmB
наполним параметрами, а так в целом сейчас норм

**Comment by Oleh-Verhulenko** [comment]
**Связь реальных и виртуальных животных**:
перепелок привязываем к местам, каждому месту присваиваем номер реальной клетки. 
Т.е. присваиваем автоматом всем местам номера клеток в оффлайне по 300 мест на одну оффлайн клетку. 
В интерфейсе отображаем это как: Номер места - 34234, номер клетки 2322

привязка к реальной клетке. В клетку помещается 200-400 птиц. Например, оффлайн клетка имеет id43, количество мест в данной клетке 300. Перепелка с id32423 привязывается к месту с id774, место с id774 привязано к клетке с id43.
Ну а дальше в клетке id43 где-то сидит перепелка с номерком на ноге id32423 (фактически этого не требуется, для перепелок не нужна персональная идентификация, достаточно номера клетки). 
Мы в свою очередь всегда знаем, что в определенной клетке должно быть точное количество перепелок.

**Comment by Oleh-Verhulenko** [comment]
**Доход:**
"доход с инкубационных яиц" начисляем каждый день согласно стоимости яйца (4,5 р.), 
за каждый день указываем количество собранных яиц, 
например 5000 яиц, от 8000 птиц, 
получаем 22500 р. на 8000 птиц 
итого на каждую 2.81р. "дохода с инкубационных яиц",

 дополнительно доход может начисляться за "доход за столовое яйцо", 
стоимость яйца 2.2р. 
а общее количество яиц на каждый день указываем вручную. 

исключили для простоты половую принадлежность птицы. Если клетка используется под яичное направление, то там не будет самцов т.к. они не нужны для столовых яиц. Если клетка под инкубационное яйцо, то самцы там присутствуют 1к3 или 1к4 самкам. доход начисляем на голову. Если клетка используется под цикл откорма до 49 дней и после идет на убой, то половая принадлежность также не имеет значения.

Еще вариант получения дохода для перепелов "Доход с помета" также начисляться в скором времени будет.

В будущем по такой же схеме будет и доход с молока начисляться у овец, коз и коров. Берем средний надой и распределяем доход.

**Comment by Oleh-Verhulenko** [comment]
**Доход:**
перепелка с 49 дня начинает нестись и спустя 240 дней ее отправляют на мясо (выкупаем за 74р.), 
а на ее место сажают новую. 

старую птицу автоматически продаем (завершился производственный цикл) и пользователю начисляем 74 рубля за птицу, место освобождается и доступно для размещения новой птицы.

опционально будем прикручивать в будущем возможность автоматической покупки или планомерного посуточного списания на протяжении всего цикла (240 дней) необходимой суммы для автообновления птицы на новую.

Чужую птицу на место пользователя поместить не можем.

Я так понимаю это нужно прикручивать именно к функционалу места. 

Вторая схема получения дохода это выращивание на мясо, с суточного возраста подращивают до 49+ дней и происходит автоматическая продажа по указанной нами цене (выкупаем перепелку за 74р.) (если в ручном режиме пользователь не выберет, например "заказать доставку на дом").

на 240 дней на убой перепела будут идти всегда (определенная крайняя точка цикла), возможно, число еще будет меняться (например, 270 дней). На 49 день идет на убой выбраковка (компенсируем необходимое количество из страхового аккаунта) и отдельно цикл есть для техасских перепелов, они мясные и их как раз подращивают до 49 дней и отправляют на мясо.

**Comment by Oleh-Verhulenko** [comment]
**Помещения:**
админ не может поменять помещение с одного вида животных на другое, он может только дополнительно добавлять или удалять места


2. Помещения можно выставить на продажу на Рынке по свободной цене. Получается, что нужно будет открыть вот этот раздел для всех на сайте 

пока этот момент терпит, чуть позже будем детально обсуждать

**Comment by Oleh-Verhulenko** [comment]
**Страховой аккаунт.**

Подробнее по Страховому аккаунту. Мы заводим отдельный аккаунт в сервисе, который в случае с перепелками используем для компенсаций и получения дополнительного дохода. Например, пользователи покупают 1000 яиц с инкубацией, фактически закладываем 2000 яиц из которых получим примерно 1500 цыплят. 1000 цыплят уходят на аккаунт пользователям, а остаток в 500 яиц на Страховой аккаунт.

**Comment by Oleh-Verhulenko** [comment]
**Добавление помещений в корзину при покупке животных**

кривое решение, согласен. Если выводить предупреждение, то нужно предусмотреть легкого добавления и помещения в корзину.

Автоматическое докидывание только при покупке - верно

**Comment by Oleh-Verhulenko** [comment]
6. Отсутвие помещения в данный момент для животного влияет как то на доход и расход приносимый животным?

нет, животное в штатном режиме приносит доход/расходы, но тогда еще необходимо предусмотреть отведенный срок для обязательной докупки мест. 

Если места к сроку не будут приобретены, производим автоматическую продажу птицы без необходимых мест.

**Comment by Oleh-Verhulenko** [comment]
8. При покупке новых животных должны ли учитываться недостающие помещения для уже существующих животных?

да, хорошо бы это как-то помечать для понимания пользователями

**Comment by Oleh-Verhulenko** [comment]
9.1. Сколько времени должно пройти со времени получения предупреждения до автопродажи?

если для перепелов необходимо место с 30 дня жизни, то автопродажа происходит в указанный срок. Активно информируем пользователя о необходимости докупки мест за 5 дней, спамим на почту, уведомляем в кабинете.

**Comment by Oleh-Verhulenko** [comment]
9.2. Что делать если пользователь не долго не заходит на сайт?

если баланс на аккаунте положительный, ничего с ним не делаем. 

А вот за неиспользование/простой мест наверняка будем включать абонентку с последующим изыманием мест при отрицательном балансе.

**Comment by Oleh-Verhulenko** [comment]
Ранее оговаривалось, что перепелов в момент достижения ими возраста, когда уже возможно определить пол, мы делим **50 на 50 (самцы/ самки)**. Это остаётся в силе?

не делим, оставляем как Взрослая птица
