### ISSUE TITLE
Создать форму заявки на вывод средств с фермы

### ISSUE THREAD

**Issue by AeroLexx** [Arbitas/Cloud-Farm#18]

**Comment by samusevalexunsued** [comment]
На тестирование
http://xn----7sbabb1a2bmfg3a0c9a0i.xn--p1ai/account/ - http://joxi.ru/82345xpidQy4AO
http://xn----7sbabb1a2bmfg3a0c9a0i.xn--p1ai/admin-requests/out-requests/
