### ISSUE TITLE
Добавить "отжатие средств" с пользователя в админке

### ISSUE THREAD

**Issue by AeroLexx** [Arbitas/Cloud-Farm#19]

**Comment by samusevalexunsued** [comment]
готово, если ввести отрицательное кол-во, у пользователя снимет деньги, изменил описание параметра в виде http://joxi.ru/a2XDOZQtegbl2g

**Comment by Oleh-Verhulenko** [comment]
Добавить коммент к каждому отжатию)))
чтобы было видно, за что деньги снялись
