### ISSUE TITLE
Добавление животных клиентам

### ISSUE THREAD

**Issue by Oleh-Verhulenko** [Arbitas/Cloud-Farm#2]
В админской части реализовать функционал, позволяющий добавлять животных в фермы пользователей и деньги им на счета.

**Comment by samusevalexunsued** [comment]
http://xn----7sbabb1a2bmfg3a0c9a0i.xn--p1ai/admin-ferma-new/temp-user-add-animal/

**Comment by Oleh-Verhulenko** [comment]
В выпадающий список животных добавить вид "Инкубационное яйцо".
