### ISSUE TITLE
Информация в карточках

### ISSUE THREAD

**Issue by Oleh-Verhulenko** [Arbitas/Cloud-Farm#23]
Нужна результирующая информация по всей группе в карточках моей фермы https://yadi.sk/i/FkqfkHge38sjwG

**Comment by AeroLexx** [comment]
Нужно проверить источник данного скриншота, есть подозрение что это из старой версии моей фермы, новый url должен быть http://xn----7sbabb1a2bmfg3a0c9a0i.xn--p1ai/my-farm/

**Comment by Oleh-Verhulenko** [comment]
https://projects.invisionapp.com/share/63607LEQP#/screens/137575865 - макет моей фермы.
Я так понимаю, что результирующая информация показана слева.
У нас такой я не нашёл - http://joxi.ru/VrwM4NYFO71a92 (облачная-ферма.рф/my-farm/)
