### ISSUE TITLE
Корзина

### ISSUE THREAD

**Issue by Oleh-Verhulenko** [Arbitas/Cloud-Farm#29]
выпадающий список в корзине неудобно сделан, нельзя выбрать 100 шт. https://yadi.sk/i/fJ3NxbRK3APQ9w

какие есть предложения?

**Comment by AeroLexx** [comment]
Мы тут видим два варианта 
1. сделать для таких "заказных" животных (количество которых неограничено) не выпадающий список, а поле для ввода кол-ва.
2. второй вариант, нужно к выпадающему списку добавить скролл и увеличить список до +100.

**Comment by Oleh-Verhulenko** [comment]
сделать для таких "заказных" животных (количество которых неограничено) не выпадающий список, а поле для ввода кол-ва - утверждено заказчиком.

**Comment by samusevalexunsued** [comment]
http://joxi.ru/8AnWBoVHpq3lrO
