### ISSUE TITLE
Редактирование страницы Контакты

### ISSUE THREAD

**Issue by Oleh-Verhulenko** [Arbitas/Cloud-Farm#3]
В админской части реализовать возможность редактирования страницы http://облачная-ферма.рф/ferma2/contacts/: добавить, редактировать, удалить информацию.

Также удалить информацию из из граф "Контактной информации"

**Comment by samusevalexunsued** [comment]
http://xn----7sbabb1a2bmfg3a0c9a0i.xn--p1ai/admin-page-editor/

на тестирование
