### ISSUE TITLE
Реквизиты

### ISSUE THREAD

**Issue by Oleh-Verhulenko** [Arbitas/Cloud-Farm#39]
Сделать страницу реквизитов (http://xn----7sbabb1a2bmfg3a0c9a0i.xn--p1ai/ferma2/contacts/) доступной для неавторизованных пользователей.

Разместить ссылку на страницу - http://xn----7sbabb1a2bmfg3a0c9a0i.xn--p1ai/ferma2/contacts/ - на главной странице.

Запросить дизайн ссылки на главной странице у дизайнера.

**Comment by Oleh-Verhulenko** [comment]
Задача дизайнеру поставлена.

**Comment by AeroLexx** [comment]
Задание сделал пока без дизайнера, ожидает выгрузки

**Comment by Oleh-Verhulenko** [comment]
http://joxi.ru/zANkgGeUBje8br - вот здесь заменить текст на "Реквизиты" и поставить ссылку на страницу с реквизитами

**Comment by Oleh-Verhulenko** [comment]
Ссылку на страницу с реквизитами разместить согласно этому шаблону - https://monosnap.com/file/tUMDTrIhTnG1mdUYaZc3Pri5UQwNHd
