### ISSUE TITLE
Видимость страницы Реквизиты

### ISSUE THREAD

**Issue by Oleh-Verhulenko** [Arbitas/Cloud-Farm#4]
Страница http://облачная-ферма.рф/ferma2/contacts/ - не доступна обычным пользователям (неадминам). Реализовать возможность простого пользователя попасть на эту страницу.

**Comment by samusevalexunsued** [comment]
Добавил доступность страницы всем пользователям.
http://xn----7sbabb1a2bmfg3a0c9a0i.xn--p1ai/ferma2/contacts/
