### ISSUE TITLE
Письма в СПАМе

### ISSUE THREAD

**Issue by Oleh-Verhulenko** [Arbitas/Cloud-Farm#53]
Разобраться с письмами, попадающими в СПАМ.

Как вариант:

Попробовать, для фермы в пхп переопределить значение из php.ini
sendmail_path со стандартного на 
sendmail_path  /usr/sbin/sendmail -t -i -f info@xn----7sbabb1a2bmfg3a0c9a0i.xn--p1ai

Return-Path: <www-data@mailer.afy.ru>
Received-SPF: pass (google.com: domain of www-data@mailer.afy.ru designates 188.120.233.221 as permitted sender) client-ip=188.120.233.221;

должны быть примерно такие записи в письме (только под наш домен и ип).
spf уже добавлен в ресурсные записи домена

**Comment by samusevalexunsued** [comment]
http://joxi.ru/Q2K40Y7ixEpgAj
на самом деле странно, должно уже заработать. как вариант ещё всё-таки настроить DKIM подпись
