### ISSUE TITLE
Кроссбраузерность

### ISSUE THREAD

**Issue by Oleh-Verhulenko** [Arbitas/Cloud-Farm#55]
Кнопка входа в браузере Опера не работает.

**Comment by AeroLexx** [comment]
Проверил данную проблему в последней, 43 версии Opera. Никаких проблем не обнаружил. Или проблемы нет или нам нужно больше подробностей о проблеме. Попробую еще порыться в понедельник

**Comment by AeroLexx** [comment]
НЕ могу найти данную проблему. На всех протестированных устройствах кнопка входа работала
