### ISSUE TITLE
Восстановление пароля

### ISSUE THREAD

**Issue by Oleh-Verhulenko** [Arbitas/Cloud-Farm#58]
http://joxi.ru/nAy94oYuY9vgOA - при восстановлении пароля, ввёл 123 - выдало ошибку.

**Comment by samusevalexunsued** [comment]
После более детального изучения проблемы оказалось что ошибка выводилась не из-за длины, а из-за того что старый и новый пароль совпадали, проверку на совпадения убрал. Проверку на длину не добавлял, это будет обсуждаться когда будем заниматься вопросами безопасности.
Сейчас (после выгрузки) все должно работать.
