### ISSUE TITLE
Скрытие данных для неадминов

### ISSUE THREAD

**Issue by Oleh-Verhulenko** [Arbitas/Cloud-Farm#59]
В списке ферм - http://joxi.ru/vAWyavlt13XgNm - данные об общей стоимости имущества и расходе в сутки не должны отображаться НЕадминам.

**Comment by samusevalexunsued** [comment]
http://joxi.ru/V2VpYLKi5Xb8rv
http://joxi.ru/vAWMyKZFMx9DmW
Также напомню что пока страница /otherfarms/ и все внутренние страницы скрыты для неадминов (для скриншота временно открыл их у себя на локальном сервере).  
Их необходимо открыть для всех пользователей?
