### ISSUE TITLE
Вывод данных в пустой корзине

### ISSUE THREAD

**Issue by Oleh-Verhulenko** [Arbitas/Cloud-Farm#6]
Если корзина пуста, то выводить ссылку на "Пополнить корзину" - https://yadi.sk/i/tIIqJrm034TaTX.
(пока уточняется будет ли это одна ссылка или несколько)

**Comment by samusevalexunsued** [comment]
http://joxi.ru/BA0OR0vCjJng2y

пока сделал так

**Comment by Oleh-Verhulenko** [comment]
https://yadi.sk/i/tIIqJrm034TaTX - при входе с планшета, работает не так, как ожидалось - ссылка не отображается.
