### ISSUE TITLE
Разобраться и навести порядок

### ISSUE THREAD

**Issue by AeroLexx** [Arbitas/Cloud-Farm#62]
Нужно почистить старые платёжные системы и собрать все в одном месте

**Comment by samusevalexunsued** [comment]
Все перенес в BankController
Тест на продакшене

**Comment by samusevalexunsued** [comment]
на продакшене "закоментировать" файлы:
Bank2Controller.php, 
FermaBankController.php, 
FermaYandexController.php, 
Mfarm2Controller.php, 
Myfarm2Controller.php, 
FermaallfarmsController.php
