### ISSUE TITLE
Ссылка на пользовательское соглашение

### ISSUE THREAD

**Issue by Oleh-Verhulenko** [Arbitas/Cloud-Farm#66]
В попапе Регистрация, под кнопкой Регистрация, расместить чек-бокс (по умолчанию активный) и текст: "Я принимаю условия [Пользовательского соглашения](http://xn----7sbabb1a2bmfg3a0c9a0i.xn--p1ai/treat.html)"

Соответсвенно, если чек-бокс неактивен - кнопка "Регистрация" тоже неактивна, то есть принятие условий - обязательно для регистрации.

**Comment by samusevalexunsued** [comment]
http://joxi.ru/52ayRzYu7jLo20
http://joxi.ru/KAxXjo9CPNdkA8
