### ISSUE TITLE
Подключение новой формы оплаты от Яндекса

### ISSUE THREAD

**Issue by Oleh-Verhulenko** [Arbitas/Cloud-Farm#7]
Сейчас доступно пополнение счета только через карточку, у Яндекса есть другая форма с выбором между карточкой, яндекс.деньгами и мобильными операторами.

https://money.yandex.ru/embed/quickpay/shop.xml?from=iget&_openstat=iget%3Bshop%3Bicon

У заказчика идентифицированный кошелёк - https://yadi.sk/i/YL3Jc98r34UK93 и это вроде как позволяется - https://money.yandex.ru/doc.xml?id=526991.

**Comment by samusevalexunsued** [comment]
http://joxi.ru/bmodvzVTYMbW2y
