### ISSUE TITLE
Инкубатор

### ISSUE THREAD

**Issue by AeroLexx** [Arbitas/Cloud-Farm#72]
Подробности реализации  и описание по ссылке 

https://docs.google.com/document/d/1If6e5XAvFWLwbdy6Va2EPN_K6GRJVTesJv2ec-mIPoY/edit#

**Comment by samusevalexunsued** [comment]
Функциональные параметры инкубатора
Дата закладки
Дата вылупления
Дата следующей закладки
Вместимость инкубатора
Минимальное количество
За яйцо и инкубацию (цена за шт.)
Выводимость (процент)
Половозрастная группа животного
