### ISSUE TITLE
Нужен кусочек дизайна

### ISSUE THREAD

**Issue by AeroLexx** [Arbitas/Cloud-Farm#78]
В соответствии с мартовским ТЗ  (http://joxi.ru/v29QnEdI3Y5gp2) нам нужен дизайн пометки о поставке в моей фермы. Что то наподобии вот этого  http://joxi.ru/EA4NZqnfwxVlMm

**Comment by Oleh-Verhulenko** [comment]
Задача дизайнеру поставлена

**Comment by Oleh-Verhulenko** [comment]
http://joxi.ru/8AnBeOzFjKbD5A - этот вариант.
