### ISSUE TITLE
Письмо о восстановлении пароля

### ISSUE THREAD

**Issue by Oleh-Verhulenko** [Arbitas/Cloud-Farm#79]
Письмо о восстановлении пароля не оформлено - http://joxi.ru/8AnBeOzFjKbbQA.
Оформить - http://joxi.ru/brRYWGecJ80wvA

**Comment by AeroLexx** [comment]
Класс отвечающий за рендер письма:
\library\User\mailer\events\RestorePassword.php

Его вызов на главной странице auth /  getrememberpopup
Сейчас письмо выглядит так http://joxi.ru/Drla9q7FvxWV7m , а должно быть адаптировано под вот этот дизайн http://joxi.ru/gmvR9d6SLn6vYm (psd макет скину по требованию).

Нужное письмо есть уже на странице   /ferma2/letters/ (в самом конце страницы)
