### ISSUE TITLE
Алёрты на сайте

### ISSUE THREAD

**Issue by Oleh-Verhulenko** [Arbitas/Cloud-Farm#8]
Использование алёртов на сайте больше не требуется. Во всех местах заменить алёрты, сообщающие об успешности действия на сайте - https://yadi.sk/i/lftIKBNm34d4hF на попап с галочкой (как сейчас реализовано при авторизации).

**Comment by samusevalexunsued** [comment]
в указанном месте (заказ продуктов) поменял, дальше буду менять по мере того как буду находить алерты
