### ISSUE TITLE
Инкубатор дизайн

### ISSUE THREAD

**Issue by AeroLexx** [Arbitas/Cloud-Farm#80]
Нужно согласовать с Романом и дизайнером новый элемент дизайна. Мы хотим в карточку инкубатора добавить SELECT с помощью которого пользователь может выбрать при заказе одну из доступных дат закладок http://joxi.ru/n2Y8VWRIoyeE9m

**Comment by Oleh-Verhulenko** [comment]
Поставил задачу дизайнеру, отписался Роману. Ждём дизайна и согласования.

**Comment by AeroLexx** [comment]
Скрин страницы инкубации http://joxi.ru/Y2L4kY0iBLpl26

**Comment by AeroLexx** [comment]
http://xn----7sbabb1a2bmfg3a0c9a0i.xn--p1ai/incubation/  старая версия
