### ISSUE TITLE
Оповещение админу

### ISSUE THREAD

**Issue by Oleh-Verhulenko** [Arbitas/Cloud-Farm#81]
В админке добавить оповещение о действиях пользователей:
Зачисление средств при пополнении счёта,
зачисление средств при продаже животных или мест,
покупка животных или мест, 
выставление на продажу животных или мест.

Визуальные и звуковые оповещения.

**Comment by AeroLexx** [comment]
1. Задачу выполнять в ветке illarionov_admin_alert (git fetch && git checkout illarionov_admin_alert)
2. Создать в БД таблицу для хранения оповещения админов admin_alerts
3. Создать новый класс канала в пространстве имён notifications\channels , который должен будет осуществлять запись всех необходимых данных в БД
4. Добавить новый канал в соответствующие события
5. Протестировать что бы все события записывались в БД
2 этап
6. В админке создаем новый контроллер AdminMessager. И под него создаём интерфейс в котором выводим уведомление из admin_alerts.
7. Админ может пометить любое из уведомлений как прочитанное
8.  Уведомления разбиты по датам, по умолчанию выводиться текущая дата, но можно переключиться на другую дату в прошлом (используй JS Datepicker)
3 этап
9. Каждую минуту, страница через AJAX запрашивает не появились ли новые уведомления. Если новые уведомления появились, то появляется кнопка "Отобразить новые уведомления" и воспроизводиться звуковой сигнал на странице. 
10. Когда пользователь нажимает на кнопку  "Отобразить новые уведомления" страница запрашивает и отображает новые уведомления с пометкой "новое".
