### ISSUE TITLE
Удаление животных

### ISSUE THREAD

**Issue by Oleh-Verhulenko** [Arbitas/Cloud-Farm#9]
На странице "Добавление животных" в Админке - https://yadi.sk/i/llZ_2H0u34cAau - реализовать возможность удалять животных у пользователей.
Это потребуется для удаления тестовых, а также погибших животных.

**Comment by samusevalexunsued** [comment]
Добавил удаление животных и групп животных у пользователя.
http://xn----7sbabb1a2bmfg3a0c9a0i.xn--p1ai/admin-user/user-add-animal/
переименовал вкладку в редактор пользователя
поскольку функионал становится постоянным сделал возвожность выбрать пользователя:
По e-mail
Id пользователя
Ссылка на пользовалетя в vk
Id пользователя в vk
Id пользователя в facebook
Id пользователя в googleplus
Id пользователя в twitter

на тестирование
